### ISSUE TITLE
is it possible to make link interactive ?

### ISSUE THREAD

**Issue by X901** [shaps80/MarkdownText#4]
Hi, 
I'm trying your library for the first time
I notice as you mention ReadMe link is non interactive

is there a way to make link interactive, so when I tap on link ,it open Safari inside app ?

**Comment by shaps80** [comment]
Not currently. The issue is to support iOS 13+ I needed to stick with `Text` which means I can't wrap it in a `Button` or add a `TapGesture`.

We can't even (AFAIK) add some kind of hit-test as we may have done with `UITextView` for example.

The only 'solution' would be to update the code to make all links 'block-based'. In that case a simple `Link` or `Button` could be used.

In order to resolve this I was exploring the idea of adding a configuration to the `MarkdownView` that would force links to become their own block, and then pushing any further inline text into a new paragraph. But I haven't had time to spend on this recently and it's a non-trivial task.

Sorry, but if you need interaction you'll need to use something else. My currently approach is one of the following:

- Don't include links in the Markdown
- Include them as text, so the whole URL is shown
- Add separate buttons in the UI that link to the appropriate locations

None of these are ideal but the point of this library wasn't to support everything, rather use pure SwiftUI to render complex formatting 👍
