### ISSUE TITLE
would like to have markdownCodeSyntaxHighlighter to support

### ISSUE THREAD

**Issue by hanrw** [shaps80/MarkdownText#9]
## Feature Description
It would be beneficial to have a designated place for configuring the code syntax highlighter. This way, developers can easily modify the code highlighter as needed.

## Problem Statement
I previously used CodeMarkdownStyle for this purpose, but it may not be ideal. For example, consider the code snippet below:
```
ScrollView(.horizontal, showsIndicators: true) {
    highlightCode(content: configuration.code, language: configuration.language)
        .padding(8)
}
```
In order to separate concerns and improve the overall structure:

## Proposed Solution
Consider the following code snippet:
```
LazyMarkdownText(message)
    .markdownCodeSyntaxHighlighter(.splash(theme: some-theme))
```

**Comment by shaps80** [comment]
I actually considered this previously and decided syntax highlighting doesn't belong in this library. Particularly because it's not easy/possible to backport as far as this library supports.

But more specifically because I feel it should be applicable to 'any' text as those other libraries imply.

It's actually easy (as you've demonstrated) to do this with the existing library, if you just provide your own code style, and then do the string parsing yourself there. Again, this is essentially what you've included already, but I don't feel it belongs in a Markdown library.

This library is focused on taking Markdown and providing the block and inline styling APIs to make it easy to work with in SwiftUI.

Syntax highlighting is an entirely unrelated step IMO.
